/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpredes.UI;

/**
 *
 * @author cc151255911
 */
public class ClienteUI extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public ClienteUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_cliente = new javax.swing.JPanel();
        p_player1 = new javax.swing.JPanel();
        lb_player1 = new javax.swing.JLabel();
        lb_name1 = new javax.swing.JLabel();
        lb_saldo1 = new javax.swing.JLabel();
        lb_saldoAtual1 = new javax.swing.JLabel();
        lb_pos1 = new javax.swing.JLabel();
        lb_posAtual1 = new javax.swing.JLabel();
        p_player2 = new javax.swing.JPanel();
        lb_player2 = new javax.swing.JLabel();
        lb_name2 = new javax.swing.JLabel();
        lb_saldo2 = new javax.swing.JLabel();
        lb_saldoAtual2 = new javax.swing.JLabel();
        lb_pos2 = new javax.swing.JLabel();
        lb_posAtual2 = new javax.swing.JLabel();
        p_player3 = new javax.swing.JPanel();
        p_player3_vazio = new javax.swing.JPanel();
        p_player3_online = new javax.swing.JPanel();
        lb_player3 = new javax.swing.JLabel();
        lb_name3 = new javax.swing.JLabel();
        lb_saldo3 = new javax.swing.JLabel();
        lb_saldoAtual3 = new javax.swing.JLabel();
        lb_pos3 = new javax.swing.JLabel();
        lb_posAtual3 = new javax.swing.JLabel();
        p_player4 = new javax.swing.JPanel();
        p_player4_vazio = new javax.swing.JPanel();
        p_player4_online = new javax.swing.JPanel();
        lb_player4 = new javax.swing.JLabel();
        lb_name4 = new javax.swing.JLabel();
        lb_saldo4 = new javax.swing.JLabel();
        lb_saldoAtual4 = new javax.swing.JLabel();
        lb_pos4 = new javax.swing.JLabel();
        lb_posAtual4 = new javax.swing.JLabel();
        p_buttons = new javax.swing.JPanel();
        tf_rdados = new javax.swing.JTextField();
        btn_rdados = new javax.swing.JButton();
        p_oferta = new javax.swing.JPanel();
        lb_proprietario = new javax.swing.JLabel();
        cb_proprietario = new javax.swing.JComboBox<>();
        lb_propriedade = new javax.swing.JLabel();
        cb_propriedade = new javax.swing.JComboBox<>();
        lb_oferta = new javax.swing.JLabel();
        tf_oferta = new javax.swing.JTextField();
        btn_go = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(530, 480));
        setResizable(false);

        p_cliente.setPreferredSize(new java.awt.Dimension(526, 430));

        p_player1.setBackground(new java.awt.Color(204, 255, 255));

        lb_player1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_player1.setText("Player1:");

        lb_name1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_name1.setText("Name1");

        lb_saldo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_saldo1.setText("Saldo:");

        lb_saldoAtual1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_saldoAtual1.setText("Saldo");

        lb_pos1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_pos1.setText("Posição:");

        lb_posAtual1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_posAtual1.setText("Posição");

        javax.swing.GroupLayout p_player1Layout = new javax.swing.GroupLayout(p_player1);
        p_player1.setLayout(p_player1Layout);
        p_player1Layout.setHorizontalGroup(
            p_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_player1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_player1Layout.createSequentialGroup()
                        .addComponent(lb_player1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_player1Layout.createSequentialGroup()
                        .addComponent(lb_saldo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_saldoAtual1))
                    .addGroup(p_player1Layout.createSequentialGroup()
                        .addComponent(lb_pos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_posAtual1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        p_player1Layout.setVerticalGroup(
            p_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_player1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_player1)
                    .addComponent(lb_name1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_saldo1)
                    .addComponent(lb_saldoAtual1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pos1)
                    .addComponent(lb_posAtual1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_player2.setBackground(new java.awt.Color(255, 204, 255));
        p_player2.setPreferredSize(new java.awt.Dimension(250, 100));

        lb_player2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_player2.setText("Player2:");

        lb_name2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_name2.setText("Name2");

        lb_saldo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_saldo2.setText("Saldo:");

        lb_saldoAtual2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_saldoAtual2.setText("Saldo");

        lb_pos2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_pos2.setText("Posição:");

        lb_posAtual2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_posAtual2.setText("Posição");

        javax.swing.GroupLayout p_player2Layout = new javax.swing.GroupLayout(p_player2);
        p_player2.setLayout(p_player2Layout);
        p_player2Layout.setHorizontalGroup(
            p_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_player2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_player2Layout.createSequentialGroup()
                        .addComponent(lb_player2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_player2Layout.createSequentialGroup()
                        .addComponent(lb_pos2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_posAtual2))
                    .addGroup(p_player2Layout.createSequentialGroup()
                        .addComponent(lb_saldo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_saldoAtual2)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        p_player2Layout.setVerticalGroup(
            p_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_player2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_player2)
                    .addComponent(lb_name2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_saldo2)
                    .addComponent(lb_saldoAtual2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pos2)
                    .addComponent(lb_posAtual2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_player3.setBackground(new java.awt.Color(255, 255, 204));
        p_player3.setPreferredSize(new java.awt.Dimension(250, 100));
        p_player3.setLayout(new java.awt.CardLayout());

        p_player3_vazio.setBackground(new java.awt.Color(255, 255, 204));
        p_player3_vazio.setPreferredSize(new java.awt.Dimension(250, 100));

        javax.swing.GroupLayout p_player3_vazioLayout = new javax.swing.GroupLayout(p_player3_vazio);
        p_player3_vazio.setLayout(p_player3_vazioLayout);
        p_player3_vazioLayout.setHorizontalGroup(
            p_player3_vazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        p_player3_vazioLayout.setVerticalGroup(
            p_player3_vazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        p_player3.add(p_player3_vazio, "card2");

        p_player3_online.setBackground(new java.awt.Color(255, 255, 0));

        lb_player3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_player3.setText("Player3:");

        lb_name3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_name3.setText("Name3");

        lb_saldo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_saldo3.setText("Saldo:");

        lb_saldoAtual3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_saldoAtual3.setText("Saldo");

        lb_pos3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_pos3.setText("Posição:");

        lb_posAtual3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_posAtual3.setText("Posição");

        javax.swing.GroupLayout p_player3_onlineLayout = new javax.swing.GroupLayout(p_player3_online);
        p_player3_online.setLayout(p_player3_onlineLayout);
        p_player3_onlineLayout.setHorizontalGroup(
            p_player3_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_player3_onlineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_player3_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_player3_onlineLayout.createSequentialGroup()
                        .addComponent(lb_player3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_player3_onlineLayout.createSequentialGroup()
                        .addComponent(lb_pos3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_posAtual3))
                    .addGroup(p_player3_onlineLayout.createSequentialGroup()
                        .addComponent(lb_saldo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_saldoAtual3)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        p_player3_onlineLayout.setVerticalGroup(
            p_player3_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_player3_onlineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_player3_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_player3)
                    .addComponent(lb_name3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_player3_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_saldo3)
                    .addComponent(lb_saldoAtual3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_player3_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pos3)
                    .addComponent(lb_posAtual3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_player3.add(p_player3_online, "card3");

        p_player4.setBackground(new java.awt.Color(204, 255, 204));
        p_player4.setPreferredSize(new java.awt.Dimension(250, 100));
        p_player4.setLayout(new java.awt.CardLayout());

        p_player4_vazio.setBackground(new java.awt.Color(204, 102, 255));
        p_player4_vazio.setPreferredSize(new java.awt.Dimension(250, 100));

        javax.swing.GroupLayout p_player4_vazioLayout = new javax.swing.GroupLayout(p_player4_vazio);
        p_player4_vazio.setLayout(p_player4_vazioLayout);
        p_player4_vazioLayout.setHorizontalGroup(
            p_player4_vazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        p_player4_vazioLayout.setVerticalGroup(
            p_player4_vazioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        p_player4.add(p_player4_vazio, "card2");

        p_player4_online.setBackground(new java.awt.Color(204, 0, 255));
        p_player4_online.setPreferredSize(new java.awt.Dimension(250, 100));

        lb_player4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_player4.setText("Player4:");

        lb_name4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_name4.setText("Name4");

        lb_saldo4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_saldo4.setText("Saldo:");

        lb_saldoAtual4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_saldoAtual4.setText("Saldo");

        lb_pos4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_pos4.setText("Posição:");

        lb_posAtual4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_posAtual4.setText("Posição");

        javax.swing.GroupLayout p_player4_onlineLayout = new javax.swing.GroupLayout(p_player4_online);
        p_player4_online.setLayout(p_player4_onlineLayout);
        p_player4_onlineLayout.setHorizontalGroup(
            p_player4_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_player4_onlineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_player4_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_player4_onlineLayout.createSequentialGroup()
                        .addComponent(lb_player4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_name4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_player4_onlineLayout.createSequentialGroup()
                        .addComponent(lb_pos4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_posAtual4))
                    .addGroup(p_player4_onlineLayout.createSequentialGroup()
                        .addComponent(lb_saldo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_saldoAtual4)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        p_player4_onlineLayout.setVerticalGroup(
            p_player4_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_player4_onlineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_player4_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_player4)
                    .addComponent(lb_name4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_player4_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_saldo4)
                    .addComponent(lb_saldoAtual4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_player4_onlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pos4)
                    .addComponent(lb_posAtual4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_player4.add(p_player4_online, "card3");

        p_buttons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tf_rdados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_rdados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_rdados.setText("Rolar Dados!");

        javax.swing.GroupLayout p_buttonsLayout = new javax.swing.GroupLayout(p_buttons);
        p_buttons.setLayout(p_buttonsLayout);
        p_buttonsLayout.setHorizontalGroup(
            p_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_rdados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_rdados)
                .addContainerGap())
        );
        p_buttonsLayout.setVerticalGroup(
            p_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_buttonsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(p_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_rdados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_rdados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_oferta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p_oferta.setToolTipText("");

        lb_proprietario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_proprietario.setText("Proprietário:");

        cb_proprietario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_proprietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name2", "Name3", "Name4" }));
        cb_proprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_proprietarioActionPerformed(evt);
            }
        });

        lb_propriedade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_propriedade.setText("Propriedade:");

        cb_propriedade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_propriedade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lb_oferta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_oferta.setText("Valor da oferta:");

        tf_oferta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_oferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ofertaActionPerformed(evt);
            }
        });

        btn_go.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_go.setText("Ir!");
        btn_go.setPreferredSize(new java.awt.Dimension(101, 31));
        btn_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_ofertaLayout = new javax.swing.GroupLayout(p_oferta);
        p_oferta.setLayout(p_ofertaLayout);
        p_ofertaLayout.setHorizontalGroup(
            p_ofertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ofertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_ofertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_ofertaLayout.createSequentialGroup()
                        .addComponent(lb_proprietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_proprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_ofertaLayout.createSequentialGroup()
                        .addGroup(p_ofertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_oferta)
                            .addComponent(lb_propriedade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_ofertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_propriedade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(p_ofertaLayout.createSequentialGroup()
                                .addComponent(tf_oferta, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_go, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_ofertaLayout.setVerticalGroup(
            p_ofertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ofertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_ofertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_go, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_ofertaLayout.createSequentialGroup()
                        .addGroup(p_ofertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_proprietario)
                            .addComponent(cb_proprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_ofertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_propriedade)
                            .addComponent(cb_propriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_ofertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_oferta)
                            .addComponent(tf_oferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout p_clienteLayout = new javax.swing.GroupLayout(p_cliente);
        p_cliente.setLayout(p_clienteLayout);
        p_clienteLayout.setHorizontalGroup(
            p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_clienteLayout.createSequentialGroup()
                        .addComponent(p_player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_clienteLayout.createSequentialGroup()
                        .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(p_buttons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_clienteLayout.createSequentialGroup()
                                .addComponent(p_player3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p_player4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p_oferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        p_clienteLayout.setVerticalGroup(
            p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_player2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_player1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p_player3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_player4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_oferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_proprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_proprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_proprietarioActionPerformed

    private void btn_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_goActionPerformed

    private void tf_ofertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ofertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ofertaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_go;
    private javax.swing.JButton btn_rdados;
    private javax.swing.JComboBox<String> cb_propriedade;
    private javax.swing.JComboBox<String> cb_proprietario;
    private javax.swing.JLabel lb_name1;
    private javax.swing.JLabel lb_name2;
    private javax.swing.JLabel lb_name3;
    private javax.swing.JLabel lb_name4;
    private javax.swing.JLabel lb_oferta;
    private javax.swing.JLabel lb_player1;
    private javax.swing.JLabel lb_player2;
    private javax.swing.JLabel lb_player3;
    private javax.swing.JLabel lb_player4;
    private javax.swing.JLabel lb_pos1;
    private javax.swing.JLabel lb_pos2;
    private javax.swing.JLabel lb_pos3;
    private javax.swing.JLabel lb_pos4;
    private javax.swing.JLabel lb_posAtual1;
    private javax.swing.JLabel lb_posAtual2;
    private javax.swing.JLabel lb_posAtual3;
    private javax.swing.JLabel lb_posAtual4;
    private javax.swing.JLabel lb_propriedade;
    private javax.swing.JLabel lb_proprietario;
    private javax.swing.JLabel lb_saldo1;
    private javax.swing.JLabel lb_saldo2;
    private javax.swing.JLabel lb_saldo3;
    private javax.swing.JLabel lb_saldo4;
    private javax.swing.JLabel lb_saldoAtual1;
    private javax.swing.JLabel lb_saldoAtual2;
    private javax.swing.JLabel lb_saldoAtual3;
    private javax.swing.JLabel lb_saldoAtual4;
    private javax.swing.JPanel p_buttons;
    private javax.swing.JPanel p_cliente;
    private javax.swing.JPanel p_oferta;
    private javax.swing.JPanel p_player1;
    private javax.swing.JPanel p_player2;
    private javax.swing.JPanel p_player3;
    private javax.swing.JPanel p_player3_online;
    private javax.swing.JPanel p_player3_vazio;
    private javax.swing.JPanel p_player4;
    private javax.swing.JPanel p_player4_online;
    private javax.swing.JPanel p_player4_vazio;
    private javax.swing.JTextField tf_oferta;
    private javax.swing.JTextField tf_rdados;
    // End of variables declaration//GEN-END:variables
}
