/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpredes.IU;

import Servidor.Servidor;
import java.net.InetAddress;
import javax.swing.table.DefaultTableModel;
import Servidor.JogadorS;

/**
 *
 * @author Foltran
 */
public class ServidorUI extends javax.swing.JFrame implements Runnable {

    private Servidor server;

    public ServidorUI() {
        initComponents();

        server = new Servidor();
        server.setUI(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_servidor = new javax.swing.JPanel();
        sp_servidor = new javax.swing.JScrollPane();
        tb_servidor = new javax.swing.JTable();
        onButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_servidor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tb_servidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IP", "Porta UDP", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp_servidor.setViewportView(tb_servidor);
        if (tb_servidor.getColumnModel().getColumnCount() > 0) {
            tb_servidor.getColumnModel().getColumn(0).setResizable(false);
            tb_servidor.getColumnModel().getColumn(1).setResizable(false);
            tb_servidor.getColumnModel().getColumn(2).setResizable(false);
        }

        onButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        onButton.setText("Ligar");
        onButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_servidorLayout = new javax.swing.GroupLayout(p_servidor);
        p_servidor.setLayout(p_servidorLayout);
        p_servidorLayout.setHorizontalGroup(
            p_servidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_servidorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_servidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp_servidor)
                    .addComponent(onButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_servidorLayout.setVerticalGroup(
            p_servidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_servidorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sp_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(onButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_servidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_servidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonActionPerformed
        //System.out.println(dS.getLocalPort() + "\n" + InetAddress.getLocalHost().getHostAddress());
        Thread t = new Thread(this);
        t.start();
        //server.escuta();
       
    }//GEN-LAST:event_onButtonActionPerformed
    
    public void atualiza(){
        DefaultTableModel model = (DefaultTableModel) this.tb_servidor.getModel();
        Object[] ob = new Object[4];

        model.setNumRows(0);
        for (JogadorS j : server.getPlayers()) {
            InetAddress ip = j.getIP();
            ob[0] = ip.getHostAddress();
            ob[1] = j.getPortaUDP();
            ob[3] = j.getStatus();

            model.addRow(ob);

        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServidorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton onButton;
    private javax.swing.JPanel p_servidor;
    private javax.swing.JScrollPane sp_servidor;
    private javax.swing.JTable tb_servidor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {

        server.escuta();
        
    }
}
